export const init_books = [
  {
    id: 1,
    photo: 'narnia.png',
    author: 'C. S. Lewis',
    title: 'The Chronicles of Narnia',
    description: 'About the experience of violence, abuse, love, loss, and femininity...',
    cover: true,
    rating: 5,
    price: '14.99',
    available: true,
    isFavorite: false,
    news: false,
    bestsaller: false,
  },
  {
    id: 2,
    photo: 'psychlogy.png',
    author: 'C. S. Lewis',
    title: 'The Chronicles of Narnia',
    description: 'About the experience of violence, abuse, love, loss, and femininity...',
    cover: true,
    rating: 5,
    price: '14.99',
    available: true,
    isFavorite: false,
    news: false,
    bestsaller: false,
  },
  {
    id: 3,
    photo: 'doriangray.png',
    author: 'C. S. Lewis',
    title: 'The Chronicles of Narnia',
    description: 'About the experience of violence, abuse, love, loss, and femininity...',
    cover: true,
    rating: 5,
    price: '14.99',
    available: true,
    isFavorite: false,
    news: false,
    bestsaller: false,
  },
  {
    id: 4,
    photo: 'subtleart.png',
    author: 'C. S. Lewis',
    title: 'The Chronicles of Narnia',
    description: 'About the experience of violence, abuse, love, loss, and femininity...',
    cover: true,
    rating: 5,
    price: '14.99',
    available: true,
    isFavorite: false,
    news: false,
    bestsaller: false,
  },
  {
    id: 5,
    photo: 'twotowers.png',
    author: 'C. S. Lewis',
    title: 'The Chronicles of Narnia',
    description: 'About the experience of violence, abuse, love, loss, and femininity...',
    cover: true,
    rating: 5,
    price: '14.99',
    available: true,
    isFavorite: false,
    news: false,
    bestsaller: false,
  },
];
